# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      # Set Django's Redis host to the Redis service name
      DJANGO_REDIS_HOST: redis

  redis:
    image: "redis:alpine" 
    ports:
      - "6379:6379" 